version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn notes_api_remade_and_extended.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migrations
  migrations:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput --username chloe --email test@nott.email"
    depends_on:
      - db